# -*- coding: utf-8 -*-
"""ml_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p8jMb2hfBHRXx4XqJpDyfpHh2gTIL4LK
"""

import os

dataset_dir = '/content/sample_data/'

# !mkdir -p {dataset_dir}

# !mkdir -p {dataset_dir}/train_images

# !unzip -q /content/subtrain_img.zip -d {dataset_dir}/train_images/

import warnings
warnings.filterwarnings("ignore")
import pandas as pd
import numpy as np
from torch.utils.data import Dataset, DataLoader
import cv2
import matplotlib.pyplot as plt
from tqdm import tqdm
import torch
import torch.nn as nn
import torchvision.models as models
from tqdm import tqdm
from sklearn.model_selection import train_test_split
import os
# !pip install segmentation-models-pytorch --quiet
import segmentation_models_pytorch as smp
from tqdm import tqdm
from sklearn.model_selection import KFold
import albumentations as A
from albumentations import (Compose, ShiftScaleRotate, Resize, RandomRotate90,
                            VerticalFlip, HorizontalFlip, OneOf, ElasticTransform,
                            GridDistortion, OpticalDistortion, CLAHE,
                            GaussNoise, ISONoise, RandomBrightnessContrast, RandomGamma)
from albumentations.pytorch import ToTensorV2
from torchvision import transforms
import time
# !pip install torch-lr-finder
from torch_lr_finder import LRFinder
from torch.optim.lr_scheduler import CosineAnnealingWarmRestarts

import os
import pandas as pd



folder_path = "/content/sample_data/train_images/subtrain_img"

# Load the train.csv file
train_df = pd.read_csv('/content/train.csv')

# Separate Image_Label into ImageId and Label
train_df[['ImageId', 'Label']] = train_df['Image_Label'].str.split('_', expand=True)
train_df = train_df.drop(columns=['Image_Label'])

image_names = {
    os.path.splitext(f)[0] + '.jpg'  # Add .jpg extension to match ImageId format in train_df
    for f in os.listdir(folder_path)
    if f.lower().endswith(".jpg")
}

# Filter train_df to keep only images that exist in the folder
common_df = train_df[train_df["ImageId"].isin(image_names)].reset_index(drop=True)



# Fill missing EncodedPixels with NaN
common_df['EncodedPixels'] = common_df['EncodedPixels'].fillna('')

# Pivot the dataframe to have one row per image
train_df = common_df.pivot(index='ImageId', columns='Label', values='EncodedPixels').reset_index()

# Fill missing values with empty strings
train_df.fillna('', inplace=True)

print(train_df.head())

# Initialize the 'fold' column to -1
train_df['fold'] = -1

# Initialize KFold
kf = KFold(n_splits=9, shuffle=True, random_state=42)

# Assign fold numbers
for fold, (train_idx, val_idx) in enumerate(kf.split(train_df)):
    train_df.loc[val_idx, 'fold'] = fold

# Now select one fold for validation (e.g., fold 0)
train_data = train_df[train_df['fold'] != 0].reset_index(drop=True)
val_data = train_df[train_df['fold'] == 0].reset_index(drop=True)

# Verify the split
print(f"Training data size: {len(train_data)}")
print(f"Validation data size: {len(val_data)}")

class CloudDataset(Dataset):
    def __init__(self, df, img_dir, mask_dir=None, transform=None, resize_shape=(416, 608), mode='train'):
        self.df = df
        self.img_dir = img_dir
        self.mask_dir = mask_dir
        self.transform = transform
        self.resize_shape = resize_shape
        self.mode = mode  # 'train', 'val', or 'test'
        self.labels = ['Fish', 'Flower', 'Gravel', 'Sugar']

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        # Get image ID
        img_id = self.df.iloc[idx]['ImageId']
        # Load image
        img_path = os.path.join(self.img_dir, img_id)
        image = cv2.imread(img_path)
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

        if self.mode != 'test':
            # Create mask
            mask = np.zeros((1400, 2100, 4), dtype=np.float32)
            for i, label in enumerate(self.labels):
                rle = self.df.iloc[idx][label]
                if rle != '':
                    mask[:, :, i] = rle2mask(rle, (1400, 2100))
            # Resize image and mask
            if self.transform:
                augmented = self.transform(image=image, mask=mask)
                image = augmented['image']
                mask = augmented['mask']
            else:
                # Resize
                image = cv2.resize(image, (self.resize_shape[1], self.resize_shape[0]))
                mask = cv2.resize(mask, (self.resize_shape[1], self.resize_shape[0]))
            # Transpose to channel-first
            image = image.transpose(2, 0, 1).astype(np.float32) / 255.0
            mask = mask.transpose(2, 0, 1).astype(np.float32)
            return torch.tensor(image), torch.tensor(mask)
        else:
            # For test mode
            if self.transform:
                augmented = self.transform(image=image)
                image = augmented['image']
            else:
                image = cv2.resize(image, (self.resize_shape[1], self.resize_shape[0]))
            image = image.transpose(2, 0, 1).astype(np.float32) / 255.0
            return torch.tensor(image), img_id

def rle2mask(rle, shape):
    '''
    Convert RLE(run length encoding) string to numpy array

    Parameters:
    rle (str): Run length encoding string
    shape (tuple): (height, width) of array to return

    Returns:
    numpy.array: Mask array
    '''
    s = rle.split()
    starts, lengths = [np.asarray(x, dtype=int) for x in (s[0:][::2], s[1:][::2])]
    starts -= 1  # Convert to zero-based indexing
    ends = starts + lengths
    img = np.zeros(shape[0]*shape[1], dtype=np.uint8)
    for lo, hi in zip(starts, ends):
        img[lo:hi] = 1
    return img.reshape(shape, order='F')  # Reshape to the original shape

train_transform = Compose([
    ShiftScaleRotate(scale_limit=0.5, rotate_limit=0, shift_limit=0.1, p=0.6, border_mode=0),
    OneOf([
        GridDistortion(p=0.5),
        OpticalDistortion(p=0.5, distort_limit=0.4, shift_limit=0.5)
    ], p=0.8),
    RandomRotate90(p=0.5),
    Resize(256, 384),
    VerticalFlip(p=0.5),
    HorizontalFlip(p=0.5),
    OneOf([
         CLAHE(p=0.8),
        GaussNoise(var_limit=(10.0, 50.0), p=0.5),
        # GaussianBlur(blur_limit=3, p=0.5),
        ISONoise(color_shift=(0.01, 0.05), intensity=(0.1, 0.5), p=0.3),
    ], p=0.8),
    RandomBrightnessContrast(p=0.8),
    RandomGamma(p=0.8)
])

val_transform = Compose([
    Resize(256, 384),
])

# Paths to your images and masks
train_img_dir = '/content/sample_data/train_images/subtrain_img'


# Create datasets
train_dataset = CloudDataset(df=train_data, img_dir=train_img_dir, transform=train_transform)
val_dataset = CloudDataset(df=val_data, img_dir=train_img_dir, transform=val_transform)

# Create dataloaders
train_loader = DataLoader(train_dataset, batch_size=1, shuffle=True, num_workers=4)
val_loader = DataLoader(val_dataset, batch_size=1, shuffle=False, num_workers=4)

print(len(train_loader))
print(len(val_loader))

# Define the model

class UNetPlusPlus(nn.Module):
    def __init__(self, encoder='timm-efficientnet-b0', num_classes=4):
        super().__init__()
        self.model = smp.UnetPlusPlus(
            encoder_name=encoder,
            encoder_weights='imagenet',
            in_channels=3,
            classes=num_classes,
            activation=None
        )

    def forward(self, x):
        return self.model(x)

# Define Dice Loss
class DiceLoss(nn.Module):
    def __init__(self):
        super(DiceLoss, self).__init__()

    def forward(self, inputs, targets, smooth=1):
        inputs = torch.sigmoid(inputs)  # Apply sigmoid to get probabilities
        inputs = inputs.view(-1)
        targets = targets.view(-1)
        intersection = (inputs * targets).sum()
        dice = (2. * intersection + smooth) / (inputs.sum() + targets.sum() + smooth)
        return 1 - dice

# Define BCE + Dice Loss
class BCEDiceLoss(nn.Module):
    def __init__(self):
        super(BCEDiceLoss, self).__init__()
        self.bce = nn.BCEWithLogitsLoss()
        self.dice = DiceLoss()

    def forward(self, inputs, targets):
        bce_loss = self.bce(inputs, targets)
        dice_loss = self.dice(inputs, targets)
        return bce_loss + dice_loss

class EarlyStopping:
    def __init__(self, patience=5, verbose=False, delta=0):
        """
        Early stops the training if validation loss doesn't improve after a given patience.
        """
        self.patience = patience
        self.verbose = verbose
        self.counter = 0
        self.best_loss = None
        self.early_stop = False
        self.delta = delta  # Minimum change to qualify as an improvement

    def __call__(self, val_loss):
        if self.best_loss is None:
            self.best_loss = val_loss
        elif val_loss > self.best_loss - self.delta:
            self.counter += 1
            if self.verbose:
                print(f'EarlyStopping counter: {self.counter} out of {self.patience}')
            if self.counter >= self.patience:
                self.early_stop = True
        else:
            self.best_loss = val_loss
            self.counter = 0

# Model initialization
model = UNetPlusPlus(encoder='timm-efficientnet-b4', num_classes=4)

# Training parameters
optimizer = torch.optim.AdamW(model.parameters(), lr=1e-4, weight_decay=1e-4)
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
    optimizer, mode='min', factor=0.5, patience=2, min_lr=1e-6)
criterion = BCEDiceLoss()


best_loss = np.inf

# Initialize early stopping
early_stopping = EarlyStopping(patience=5, verbose=True)

# Move the model to the first GPU (as the base device)

device = torch.device("cpu")
if torch.cuda.is_available():
    device = torch.device("cuda")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")

model = model.to(device)

# Wrap the model in DataParallel to utilize all available GPUs
if torch.cuda.device_count() > 1:
    print(f"Using {torch.cuda.device_count()} GPUs!")
    model = nn.DataParallel(model)

num_epochs = 2

for epoch in range(num_epochs):
    model.train()
    train_loss = 0
    with tqdm(total=len(train_loader), desc=f'Epoch {epoch+1}/{num_epochs}', unit='batch') as pbar:
        for images, masks in train_loader:
            images = images.to(device)
            masks = masks.to(device)

            optimizer.zero_grad()
            outputs = model(images)
            loss = criterion(outputs, masks)
            loss.backward()
            optimizer.step()

            train_loss += loss.item()
            pbar.set_postfix({'loss': loss.item()})
            pbar.update(1)

    avg_train_loss = train_loss / len(train_loader)

    # Validation
    model.eval()
    val_loss = 0
    with torch.no_grad():
        for images, masks in val_loader:
            images = images.to(device)
            masks = masks.to(device)
            outputs = model(images)
            loss = criterion(outputs, masks)
            val_loss += loss.item()

    avg_val_loss = val_loss / len(val_loader)

    # Scheduler step (based on epoch progress, not validation loss)
    scheduler.step(epoch + (1 / len(train_loader)))  # Use a fractional step for more precision if needed

    # Evaluate
    print(f'Epoch [{epoch+1}/{num_epochs}], Train Loss: {avg_train_loss:.4f}, Val Loss: {avg_val_loss:.4f}')

    # Save the model if validation loss has decreased
    if avg_val_loss < best_loss:
        best_loss = avg_val_loss
        torch.save(model.state_dict(), 'best_model.pth')
        print('Validation loss decreased. Model saved!')

    # Check early stopping
    early_stopping(avg_val_loss)
    if early_stopping.early_stop:
        print('Early stopping triggered. Stopping training.')
        break

